### ISSUE TITLE
Repository Download link requires authentication

### ISSUE THREAD

**Issue by jonas-l** [enen92/program.plexus#95]
_Repository Download_ link in [Home / Addon installation](https://github.com/enen92/program.plexus/wiki#addon-installation) page points to http://p2p-strm.googlecode.com/svn/addons/repository.p2p-streams.xbmc/repository.p2p-streams.xbmc-1.0.4.zip which asks for authentication.

**Comment by enen92** [comment]
No more support to p2p-streams, the project is dead.
